# Generated by Django 4.1.2 on 2022-10-12 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
